// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7H79e-2VSBI08ZL2jqTKoPHFw8GH2FFQ',
    appId: '1:170255090219:web:994cca2966e6212a59206e',
    messagingSenderId: '170255090219',
    projectId: 'splitwise-92170',
    authDomain: 'splitwise-92170.firebaseapp.com',
    storageBucket: 'splitwise-92170.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9dywNFtLaZVcS0p-OhsWBz6nM3NYlGzU',
    appId: '1:170255090219:android:64f34eb4b0d5775759206e',
    messagingSenderId: '170255090219',
    projectId: 'splitwise-92170',
    storageBucket: 'splitwise-92170.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgFwftuSxFDB5tk53zsDGWpdJFPvQ_Ug',
    appId: '1:170255090219:ios:fa06a5397c38354f59206e',
    messagingSenderId: '170255090219',
    projectId: 'splitwise-92170',
    storageBucket: 'splitwise-92170.appspot.com',
    iosBundleId: 'com.example.splitwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgFwftuSxFDB5tk53zsDGWpdJFPvQ_Ug',
    appId: '1:170255090219:ios:7e4a788c9e86623959206e',
    messagingSenderId: '170255090219',
    projectId: 'splitwise-92170',
    storageBucket: 'splitwise-92170.appspot.com',
    iosBundleId: 'com.example.splitwise.RunnerTests',
  );
}
